### PR TITLE
Middleware

### PR DESCRIPTION
**Pull request by gurgeous**
first pass at listing interesting middleware. (see https://github.com/lostisland/faraday/discussions/1270)

### CODE REVIEW

**Review by olleolleolle — APPROVED** [review]
Super!

One typographic thing I would want us to keep doing: uppercase terms like `HTTP` and `XML`, `UTF-8` and `JSON`.

**Comment by gurgeous** [comment]
Sure - how about this?

**Comment by gurgeous** [comment]
Ping, just want to make sure this one is still in the pipeline. There's a link to it now... :)

**Comment by olleolleolle** [comment]
One note: the wording "curated list" - does that refer to the built-in Faraday middlewares? We want to convey the idea that they're more "soldered-on" at the moment, more than "finely curated". The next major would like to have fewer middlewares baked-in, so, as a strategic side-step around that, perhaps we can refer to the current set of Faraday gem middlewares as the built-in set?

**Comment by olleolleolle** [comment]
I think we should merge this in, and have this big, navigable list available!

**Comment by gurgeous** [comment]
> One note: the wording "curated list" - does that refer to the built-in Faraday middlewares? We want to convey the idea that they're more "soldered-on" at the moment, more than "finely curated". The next major would like to have fewer middlewares baked-in, so, as a strategic side-step around that, perhaps we can refer to the current set of Faraday gem middlewares as the built-in set?

My wording was confusing. I was trying to explain that the `awesome-faraday` repo doesn't list all Faraday middleware. The first version of our "curated list"  was mostly determined by searching rubygems.org. Do you think I should re-word this bit?

`In addition to our curated list of middleware, we would like to specifically call your attention to middleware that is helpful for general HTTP use...`

Maybe:

`We would also like to specifically call your attention to middleware that is helpful for general HTTP use...`

?

**Comment by olleolleolle** [comment]
Aha, then perhaps "this curated list of ..." is a wording which encapsulates that?

**Comment by gurgeous** [comment]
Better?

**Pull request merged**
